export const MEMBERS_ACTIONS_TYPES = {
   GET_MEMBERS_START: 'GET_MEMBERS_START',
   GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
   GET_MEMBERS_FAIL: 'GET_MEMBERS_FAIL',

   UPDATE_MEMBER_START: 'UPDATE_MEMBER_START',
   UPDATE_MEMBER_SUCCESS: 'UPDATE_MEMBER_SUCCESS',
   UPADTE_MEMBER_FAIL: 'UPADTE_MEMBER_FAIL',

   ADD_MEMBER_START: 'ADD_MEMBER_START',
   ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
   ADD_MEMBER_FAIL: 'ADD_MEMBER_FAIL',

   DELETE_MEMBER_START: 'DELETE_MEMBER_START',
   DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
   DELETE_MEMBER_FAIL: 'DELETE_MEMBER_FAIL',
}