export const SUBS_ACTIONS_TYPES = {
   ADD_SUB_START: 'ADD_SUB_START',
   ADD_SUB_SUCCESS_MOVIES: 'ADD_SUB_SUCCESS_MOVIES',
   ADD_SUB_SUCCESS_MEMBERS: 'ADD_SUB_SUCCESS_MEMBERS',
   ADD_SUB_FAIL: 'ADD_SUB_FAIL'
}