export const AUTH_ACTIONS_TYPES = {
   AUTH_REGISTER_START: 'AUTH_REGISTER_START',
   AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
   AUTH_REGISTER_FAIL: 'AUTH_REGISTER_FAIL',

   AUTH_LOGIN_START: 'AUTH_LOGIN_START',
   AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
   AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',

   AUTH_USER_START: 'AUTH_USER_START',
   AUTH_USER_SECCESS: 'AUTH_USER_SECCESS',
   AUTH_USER_FAIL: 'AUTH_USER_FAIL',

   AUTH_LOGOUT_START: 'AUTH_LOGOUT_START',
   AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
   AUTH_LOGOUT_FAIL: 'AUTH_LOGOUT_FAIL'
}