export const USERS_ACTIONS_TYPES = {
   GET_USERS_START: 'GET_USERS_START',
   GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
   GET_USERS_FAIL: 'GET_USERS_FAIL',

   ADD_USER_START: 'ADD_USER_START',
   ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
   ADD_USER_FAIL: 'ADD_USER_FAIL',

   DELETE_USER_START: 'DELETE_USER_START',
   DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
   DELETE_USER_FAIL: 'DELETE_USER_FAIL',

   UPDATE_USER_START: 'UPDATE_USER_START',
   UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
   UPADTE_USER_FAIL: 'UPADTE_USER_FAIL'
}