export const MOVIES_ACTIONS_TYPES = {
   GET_MOVIES_START: 'GET_MOVIES_START',
   GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
   GET_MOVIES_FAIL: 'GET_MOVIES_FAIL',

   UPDATE_MOVIE_START: 'UPDATE_MOVIE_START',
   UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
   UPADTE_MOVIE_FAIL: 'UPADTE_MOVIE_FAIL',

   ADD_MOVIE_START: 'ADD_MOVIE_START',
   ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
   ADD_MOVIE_FAIL: 'ADD_MOVIE_FAIL',

   DELETE_MOVIE_START: 'DELETE_MOVIE_START',
   DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
   DELETE_MOVIE_FAIL: 'DELETE_MOVIE_FAIL',

}